### ISSUE TITLE
NOTHING WRONG WITH THE PROCJECT JUST SOME RANDOM HATER

### ISSUE THREAD

**Issue by 15Fryterittos** [kir-55/Chess#1]

**Comment by kir-55** [comment]
YOUR MOTHER DOESNT LOVE YOU

**Comment by kir-55** [comment]
fUCCK OF OR I WILL UNFOLLOW YOU

**Comment by 15Fryterittos** [comment]
BRO AT LEAST I HAVE A MOTHER AND I KNOW THAT GUY LIKE YOU WITHOUT PARENTS WILL SHOUT AT SOMEONE WHO HAS PARENTS NOT LIKE YOU BECAUSE YOU HAVE NO FAMILIE, FRIENDS AND NOBODY LIKES YOU FRICKING NUGGET

**Comment by kir-55** [comment]
thats.. so.... so sad(

**Comment by kir-55** [comment]
whty are you like this bro

**Comment by kir-55** [comment]
you are hater of beginers
